In [2]:
import pandas as pd
import numpy as np

In [7]:
# 1. Criação de uma lista e tupla combinada
lista = [1,2,3,4,5]

tupla = tuple(lista)
tupla

(1, 2, 3, 4, 5)

In [8]:
arr = np.array(tupla)
arr

array([1, 2, 3, 4, 5])

In [12]:
# media = np.mean(arr)
# media
media = arr.mean()
media


3.0

In [18]:
# 2. Operações com Pandas Series: 

# paises = pd.Series(['brasil', 'EUA', 'Inglaterra'])
# paises
paises = ['Brasil', 'EUA', 'Inglaterra']
paises_data = pd.Series(paises)
paises_data

0        Brasil
1           EUA
2    Inglaterra
dtype: object

In [35]:
pop = [210000000, 300000000, 8000000]
pop_series = pd.Series(pop, index=paises)
pop_series

Brasil        210000000
EUA           300000000
Inglaterra      8000000
dtype: int64

In [41]:
# pop_media = np.mean(pop_series)
pop_media = pop_series.mean()
pop_media

172666666.66666666

In [42]:
# 3. Manipulação de listas e tuplas com NumPy:

arr = [1,2,3,4,5,6,7,8,9,10]
arr_num = np.array(arr)

arr_num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
minimo = np.min(arr_num)

minimo

5.5

In [45]:
maximo = np.max(arr_num)

maximo

10

In [46]:
media = np.mean(arr_num)

media

5.5

In [13]:
# 4. Concatenação de Pandas Series: 

lista1 = [1,2,3,4,5]
lista2 = [6,7,8,9,10]

conc1 = pd.Series(lista1)
# print(conc1)
conc2 = pd.Series(lista2)
# print(conc2)

# concatenacao = conc1, conc2
concatenacao = pd.concat([conc1, conc2])

concatenacao

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

In [60]:
concatenacao = conc1 + conc2

conc_media = concatenacao.mean()
conc_media

11.0

In [61]:
# 5. Operações entre Pandas Series e NumPy:

lista1 = [1,2,3,4,5]

lista_pandas = pd.Series(lista1)
lista_pandas

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [62]:
lista_numpy = np.array(lista_pandas)
lista_numpy

array([1, 2, 3, 4, 5], dtype=int64)

In [67]:
mult = lista_numpy * 3
mult

array([ 3,  6,  9, 12, 15], dtype=int64)

In [69]:
pandas_num = pd.Series(mult)
pandas_num

0     3
1     6
2     9
3    12
4    15
dtype: int64